# Generated by Django 3.2.12 on 2025-03-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipie_name', models.CharField(max_length=100)),
                ('recipie_description', models.TextField()),
                ('recipie_image', models.ImageField(default='', upload_to='recipie ')),
            ],
        ),
    ]
